"""
RESOLVIT - Premium Export & Reporting Routes
Supports CSV, Excel, and Professional Branded PDF exports.
Enforces strict security: users only export their own reports.
"""

import io
import pandas as pd
from typing import Optional
from fastapi import APIRouter, HTTPException, Depends, Query, Response
from fastapi.responses import StreamingResponse
from datetime import datetime, timezone
from fpdf import FPDF
from database import get_db
from auth import get_current_user

router = APIRouter()

# ─────────────────────────────────────────────────────────────
# PDF ENGINE (FPDF2)
# ─────────────────────────────────────────────────────────────

class ResolvitPDF(FPDF):
    def header(self):
        # Premium Branded Header
        self.set_fill_color(15, 12, 41) # Deep RESOLVIT Blue
        self.rect(0, 0, 210, 40, 'F')
        
        self.set_font('helvetica', 'B', 24)
        self.set_text_color(255, 255, 255)
        self.cell(0, 20, '   RESOLVIT', ln=True, align='L')
        
        self.set_font('helvetica', '', 10)
        self.set_text_color(148, 163, 184)
        self.cell(0, -10, '   CIVIC RESOLUTION PLATFORM | REPORT HISTORY   ', ln=True, align='L')
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by RESOLVIT Engine on {datetime.now().strftime("%Y-%m-%d %H:%M")}', align='C')

def create_issue_pdf(issues, user):
    pdf = ResolvitPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    # User Summary
    pdf.set_font('helvetica', 'B', 16)
    pdf.set_text_color(15, 12, 41)
    pdf.cell(0, 10, f'Citizen Report: {user["full_name"] or user["username"]}', ln=True)
    
    pdf.set_font('helvetica', '', 10)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 8, f'Email: {user["email"]}', ln=True)
    pdf.cell(0, 8, f'Total Records: {len(issues)}', ln=True)
    pdf.ln(10)
    
    # Issue Cards in PDF
    for issue in issues:
        # Card Border/Box
        pdf.set_draw_color(226, 232, 240)
        pdf.set_fill_color(248, 250, 252)
        pdf.rect(pdf.get_x(), pdf.get_y(), 190, 45, 'FD')
        
        # Priority/Category
        pdf.set_font('helvetica', 'B', 9)
        pdf.set_text_color(99, 102, 241) # Accent color
        pdf.cell(95, 8, f'  {issue["category"].upper()}', ln=False)
        
        # Status Badge
        status_color = (34, 197, 94) if issue["status"] == "resolved" else (249, 115, 22)
        pdf.set_text_color(*status_color)
        pdf.cell(90, 8, f'STATUS: {issue["status"].upper()}  ', ln=True, align='R')
        
        # Title
        pdf.set_font('helvetica', 'B', 12)
        pdf.set_text_color(15, 12, 41)
        pdf.cell(0, 8, f'  {issue["title"][:70]}...', ln=True)
        
        # Meta row
        pdf.set_font('helvetica', '', 8)
        pdf.set_text_color(100, 116, 139)
        created = issue["created_at"].strftime("%Y-%m-%d") if isinstance(issue["created_at"], datetime) else str(issue["created_at"])
        pdf.cell(95, 6, f'  Track ID: {str(issue["id"])[:13]}', ln=False)
        pdf.cell(90, 6, f'Reported: {created}  ', ln=True, align='R')
        
        # Description excerpt
        pdf.set_font('helvetica', '', 9)
        pdf.set_text_color(51, 65, 85)
        desc = issue["description"].replace('\n', ' ')
        pdf.multi_cell(0, 5, f'  Summary: {desc[:280]}...', ln=True)
        
        pdf.ln(12) # Gap between cards

    return pdf.output()

# ─────────────────────────────────────────────────────────────
# EXPORT ENDPOINTS
# ─────────────────────────────────────────────────────────────

@router.get("/issues/csv")
async def export_issues_csv(
    status: Optional[str] = None,
    category: Optional[str] = None,
    current_user: dict = Depends(get_current_user)
):
    """Secure CSV Export for current user's issues."""
    query = "SELECT * FROM issues WHERE reporter_id = %s"
    params = [current_user["sub"]]
    
    if status:
        query += " AND status = %s"
        params.append(status)
    if category:
        query += " AND category = %s"
        params.append(category)
        
    query += " ORDER BY created_at DESC"
    
    with get_db() as cursor:
        cursor.execute(query, tuple(params))
        rows = cursor.fetchall()

    if not rows:
        raise HTTPException(status_code=404, detail="No reports found for export.")

    df = pd.DataFrame(rows)
    
    # Sanitize for export
    if "reporter_id" in df.columns: df.drop(columns=["reporter_id"], inplace=True)
    
    output = io.StringIO()
    df.to_csv(output, index=False)
    
    return Response(
        content=output.getvalue(),
        media_type="text/csv",
        headers={"Content-Disposition": f"attachment; filename=resolvit_reports_{datetime.now().strftime('%Y%m%d')}.csv"}
    )

@router.get("/issues/pdf")
async def export_issues_pdf(
    current_user: dict = Depends(get_current_user)
):
    """Secure Premium PDF Export for current user's issue history."""
    with get_db() as cursor:
        # Get User details for the PDF header
        cursor.execute("SELECT username, full_name, email FROM users WHERE id = %s", (current_user["sub"],))
        user_data = cursor.fetchone()
        
        # Get Issues
        cursor.execute("SELECT * FROM issues WHERE reporter_id = %s ORDER BY created_at DESC", (current_user["sub"],))
        issues = cursor.fetchall()

    if not issues:
        raise HTTPException(status_code=404, detail="No reports found for export.")

    pdf_bytes = create_issue_pdf(issues, user_data)
    
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename=resolvit_report_history_{datetime.now().strftime('%Y%m%d')}.pdf"}
    )

@router.get("/issue/{issue_id}/pdf")
async def export_single_issue_pdf(
    issue_id: str,
    current_user: dict = Depends(get_current_user)
):
    """Export a single issue as a 'Certificate of Submission' or Full Report."""
    with get_db() as cursor:
        cursor.execute("SELECT username, full_name, email FROM users WHERE id = %s", (current_user["sub"],))
        user_data = cursor.fetchone()
        
        cursor.execute("SELECT * FROM issues WHERE id = %s", (issue_id,))
        issue = cursor.fetchone()

    if not issue:
        raise HTTPException(status_code=404, detail="Issue not found.")
        
    # Security check: User can only download their own issue unless Admin
    if str(issue["reporter_id"]) != current_user["sub"] and current_user["role"] != "admin":
        raise HTTPException(status_code=403, detail="Unauthorized export request.")

    pdf_bytes = create_issue_pdf([issue], user_data)
    
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename=resolvit_issue_{issue_id[:8]}.pdf"}
    )
